CREATE TABLE site_info (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    entry TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);